### ISSUE TITLE
Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function

### ISSUE THREAD

**Issue by benjamine** [atom-minimap/minimap#404]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.16.0

### Stack Trace

Uncaught TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function

```
At /Users/benja/.atom/packages/minimap/lib/minimap.coffee:200

TypeError: this.textEditor.displayBuffer.getMaxScrollTop is not a function
  at Minimap.module.exports.Minimap.getTextEditorMaxScrollTop (/Users/benja/.atom/packages/minimap/lib/minimap.coffee:196:3)
  at Minimap.module.exports.Minimap.getTextEditorScrollRatio (/Users/benja/.atom/packages/minimap/lib/minimap.coffee:212:30)
  at Minimap.module.exports.Minimap.getCapedTextEditorScrollRatio (/Users/benja/.atom/packages/minimap/lib/minimap.coffee:217:39)
  at Minimap.module.exports.Minimap.getScrollTop (/Users/benja/.atom/packages/minimap/lib/minimap.coffee:16:3)
  at Minimap.module.exports.Minimap.getLastVisibleScreenRow (/Users/benja/.atom/packages/minimap/lib/minimap.coffee:325:22)
  at Minimap.module.exports.DecorationManagement.emitRangeChanges (/Users/benja/.atom/packages/minimap/lib/mixins/decoration-management.coffee:271:31)
  at Minimap.module.exports.DecorationManagement.emitDecorationChanges (/Users/benja/.atom/packages/minimap/lib/mixins/decoration-management.coffee:263:6)
  at Minimap.module.exports.DecorationManagement.decorateMarker (/Users/benja/.atom/packages/minimap/lib/mixins/decoration-management.coffee:225:6)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.markRange (/Users/benja/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:63:14)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.addDecorations (/Users/benja/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:49:10)
  at MinimapGitDiffBinding.module.exports.MinimapGitDiffBinding.updateDiffs (/Users/benja/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:42:8)
  at /Users/benja/.atom/packages/minimap-git-diff/lib/minimap-git-diff-binding.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1276:25

```

### Commands

```
     -0:39.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:33.8.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:29.3.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:27.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.4.0 core:paste (atom-text-editor.editor.is-focused)
 16x -0:25.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:24.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:24 core:delete (atom-text-editor.editor.is-focused)
     -0:23.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:07.2.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  4x -0:06.8.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:06.2.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:copy (atom-text-editor.editor.is-focused)
 17x -0:05.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "ide-flow",
      "linter-jscs"
    ],
    "projectHome": "/Users/benja/proj"
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true,
      "git-diff": true,
      "minimap-autohide": true
    }
  }
}
```

### Installed Packages

```coffee
# User
Tern, v0.8.0
atom-beautify, v0.28.16
autoclose-html, v0.19.0
cucumber, v0.5.0
editor-stats, v0.17.0
editorconfig, v1.2.1
file-icons, v1.6.11
highlight-selected, v0.10.1
language-gherkin, v1.0.3
language-jade, v0.6.2
language-nginx, v0.6.1
linter, v1.10.0
linter-flow, v3.1.3
linter-jshint, v1.2.1
linter-less, v2.2.0
minimap, v4.16.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
node-debugger, v1.1.9
node-resolver, v1.0.1
svg-preview, v0.6.1
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by miclaus** [comment]
+1

**Comment by colinfike** [comment]
I'm reporting the same issue.

**Comment by kbmmdwork** [comment]
+1

**Comment by tiwu** [comment]
same issue here

**Comment by emiliocampa-hoyos** [comment]
+1

**Comment by diazmartin** [comment]
+1

**Comment by lforge** [comment]
I have uninstalled the package and reinstall it from the Atom package screen and it seems to have resolved this problem.  Give it a try.  Thanks.

**Comment by emiliocampa-hoyos** [comment]
Just delete package and install it again, that should solve the error.

**Comment by kbmmdwork** [comment]
emiliocampa-hoyos, that worked for me... why was that necessary though?

**Comment by abe33** [comment]
Minimap, as well as Pigments, uses custom elements, and custom elements can't be unregistered nor updated using the current APIs.
Until v4.16 no update mechanism was implemented to handle that case. In the latest version I introduced a new mechanism that should allow to update custom elements when updating the package within Atom, sadly it will only effective on the next release. We'll see how it plays, but I'm confident this kind of issue should gradually disappear.

Agai, I'm really sorry for the inconvenience, I understand how frustrating it can be for you.

**Comment by kbmmdwork** [comment]
To be honest with you this issue wasn't the most frustrating thing, so no big deal.  My biggest issue with Atom right now is that there's no way to prevent auto-update.  I've run into an issue with Atom 1.1 where it crashes continually with a project with many files in the node_modules folder... so I absolutely can't use it in these scenarios.  Very frustrating!

**Comment by abe33** [comment]
Oh yes, this must be seriously annoying, I'm always on a version built from the repo (because I need to follow master's changes to plan the update needed in the various packages I maintain). I'm surprised it was still not adressed though.

**Comment by miclaus** [comment]
uninstalling the minimap package, then reloading from the menu and reinstalling minimap did it for me .
